# Generated by Django 2.2.28 on 2024-01-19 11:29

from django.db import (
    migrations,
    models,
)

import edulib.core.base.files


class Migration(migrations.Migration):

    dependencies = [
        ('library_event', '0002_auto_20180420_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryevent',
            name='file',
            field=models.FileField(blank=True, max_length=255, upload_to=edulib.core.base.files.upload_file_handler, verbose_name='Приложения'),
        ),
    ]
