import os

CONFIG_KEY = "alphasense"
ALPHASENSE_USERNAME = "ALPHASENSE_USERNAME"
ALPHASENSE_PASSWORD = "ALPHASENSE_PASSWORD"
ALPHASENSE_API_KEY = "ALPHASENSE_API_KEY"
ALPHASENSE_API_URL = "ALPHASENSE_API_URL"
ALPHASENSE_API_ENDPOINT = "ALPHASENSE_API_ENDPOINT"
ALPHASENSE_GRAPHQL_SCHEMA_ENDPOINT = "ALPHASENSE_GRAPHQL_SCHEMA_ENDPOINT"
ALPHASENSE_CLIENT_ID = "ALPHASENSE_CLIENT_ID"
ALPHASENSE_CLIENT_SECRET = "ALPHASENSE_CLIENT_SECRET"
ALPHASENSE_GRAPHQL_SCHEMA_ENDPOINT = "ALPHASENSE_GRAPHQL_SCHEMA_ENDPOINT"
ALPHASENSE_HEADER_X_API_KEY = "X-Api-Key"

ALPHASENSE_CONFIG_FILE = "ALPHASENSE_CONFIG_FILE"
DEFAULT_CONFIG_FILE_PATH = os.environ.get(ALPHASENSE_CONFIG_FILE, "pyproject.toml")
