# coding: utf-8

"""
    UiPath.WebApi 18.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 18.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import uipath_orchestrator_rest
from uipath_orchestrator_rest.models.machine_deleted_event import MachineDeletedEvent  # noqa: E501
from uipath_orchestrator_rest.rest import ApiException


class TestMachineDeletedEvent(unittest.TestCase):
    """MachineDeletedEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMachineDeletedEvent(self):
        """Test MachineDeletedEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = uipath_orchestrator_rest.models.machine_deleted_event.MachineDeletedEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
