# coding: utf-8

"""
    UiPath.WebApi 18.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 18.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import uipath_orchestrator_rest
from uipath_orchestrator_rest.api.task_forms_api import TaskFormsApi  # noqa: E501
from uipath_orchestrator_rest.rest import ApiException


class TestTaskFormsApi(unittest.TestCase):
    """TaskFormsApi unit test stubs"""

    def setUp(self):
        self.api = uipath_orchestrator_rest.api.task_forms_api.TaskFormsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_task_forms_bulk_complete_tasks(self):
        """Test case for task_forms_bulk_complete_tasks

        Bulk Complete the task by merging form data and action taken  # noqa: E501
        """
        pass

    def test_task_forms_bulk_update_tasks(self):
        """Test case for task_forms_bulk_update_tasks

        Bulk Update Task data by merging data.  # noqa: E501
        """
        pass

    def test_task_forms_complete_task(self):
        """Test case for task_forms_complete_task

        Complete the task by saving form data and action taken  # noqa: E501
        """
        pass

    def test_task_forms_create_form_task(self):
        """Test case for task_forms_create_form_task

        Creates a new Form Task.  # noqa: E501
        """
        pass

    def test_task_forms_get_task_data_by_id(self):
        """Test case for task_forms_get_task_data_by_id

        Returns task data dto  # noqa: E501
        """
        pass

    def test_task_forms_get_task_form_by_id(self):
        """Test case for task_forms_get_task_form_by_id

        Returns form dto to render task form  # noqa: E501
        """
        pass

    def test_task_forms_save_and_reassign_task(self):
        """Test case for task_forms_save_and_reassign_task

        Save changes done by the current user and Reassign Task to another user  # noqa: E501
        """
        pass

    def test_task_forms_save_task_data(self):
        """Test case for task_forms_save_task_data

        Save task data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
