# coding: utf-8

"""
    UiPath.WebApi 18.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 18.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import uipath_orchestrator_rest
from uipath_orchestrator_rest.api.webhooks_api import WebhooksApi  # noqa: E501
from uipath_orchestrator_rest.rest import ApiException


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self):
        self.api = uipath_orchestrator_rest.api.webhooks_api.WebhooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_webhooks_delete_by_id(self):
        """Test case for webhooks_delete_by_id

        Delete a webhook subscription  # noqa: E501
        """
        pass

    def test_webhooks_get(self):
        """Test case for webhooks_get

        List webhooks  # noqa: E501
        """
        pass

    def test_webhooks_get_by_id(self):
        """Test case for webhooks_get_by_id

        Gets a single webhook  # noqa: E501
        """
        pass

    def test_webhooks_get_event_types(self):
        """Test case for webhooks_get_event_types

        Gets the list of event types a webhook can subscribe to  # noqa: E501
        """
        pass

    def test_webhooks_patch_by_id(self):
        """Test case for webhooks_patch_by_id

        Patches a webhook  # noqa: E501
        """
        pass

    def test_webhooks_ping_by_id(self):
        """Test case for webhooks_ping_by_id

        Sends a Ping request to webhook endpoint.  Used for testing connectivity and availability of target URL  # noqa: E501
        """
        pass

    def test_webhooks_post(self):
        """Test case for webhooks_post

        Create a new webhook subscription  # noqa: E501
        """
        pass

    def test_webhooks_put_by_id(self):
        """Test case for webhooks_put_by_id

        Update an existing webhook subscription  # noqa: E501
        """
        pass

    def test_webhooks_trigger_custom(self):
        """Test case for webhooks_trigger_custom

        Triggers an event of type \"custom\"  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
