"""
    EMIL CustomerService

    The EMIL CustomerService API description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@emil.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eis.customers
from eis.customers.model.create_payment_method_request_dto import CreatePaymentMethodRequestDto
from eis.customers.model.policy_object_dto import PolicyObjectDto
globals()['CreatePaymentMethodRequestDto'] = CreatePaymentMethodRequestDto
globals()['PolicyObjectDto'] = PolicyObjectDto
from eis.customers.model.update_lead_request_dto import UpdateLeadRequestDto


class TestUpdateLeadRequestDto(unittest.TestCase):
    """UpdateLeadRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateLeadRequestDto(self):
        """Test UpdateLeadRequestDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateLeadRequestDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
