__app_name__ = "LinkChecker"
__version__ = "10.5.0"
__release_date__ = "2024-09-03"
__copyright_year__ = "2024"
__author__ = "LinkChecker Authors"
__url__ = "https://linkchecker.github.io/linkchecker/"
__support_url__ = "https://github.com/linkchecker/linkchecker/issues"
