# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shutdown.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0eshutdown.proto\x12\x11insta360.messages"\xaa\x01\n\x14NotificationShutdown\x12\x45\n\nerror_code\x18\x01 \x01(\x0e\x32\x31.insta360.messages.NotificationShutdown.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t":\n\tErrorCode\x12\x12\n\x0e\x42\x41TTERT_RUNOUT\x10\x00\x12\x19\n\x15TEMPERATURE_OVERLIMIT\x10\x01\x42\x08\xa2\x02\x05INSPBb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "shutdown_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"\242\002\005INSPB"
    _globals["_NOTIFICATIONSHUTDOWN"]._serialized_start = 38
    _globals["_NOTIFICATIONSHUTDOWN"]._serialized_end = 208
    _globals["_NOTIFICATIONSHUTDOWN_ERRORCODE"]._serialized_start = 150
    _globals["_NOTIFICATIONSHUTDOWN_ERRORCODE"]._serialized_end = 208
# @@protoc_insertion_point(module_scope)
