# Generated by Django 1.9.13 on 2018-11-15 08:33
import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('lib_registry', '0009_move_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='libregistryentry',
            name='author_sign',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='\u0430\u0432\u0442\u043e\u0440\u0441\u043a\u0438\u0439 \u0437\u043d\u0430\u043a'),
        ),
        migrations.AddField(
            model_name='libregistryentry',
            name='bbc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.Catalog', verbose_name='\u0440\u0430\u0437\u0434\u0435\u043b \u0411\u0411\u041a'),
        ),
        migrations.AddField(
            model_name='libregistryexample',
            name='employee_fullname',
            field=models.CharField(blank=True, default=b'', max_length=50, null=True, verbose_name='\u0424\u0418\u041e \u0441\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='libregistryexample',
            name='employee_phone',
            field=models.CharField(blank=True, default=b'', max_length=50, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u0441\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='libregistryexample',
            name='writeoff_reason',
            field=models.SmallIntegerField(blank=True, choices=[(0, '\u0423\u0441\u0442\u0430\u0440\u0435\u0432\u0448\u0430\u044f \u043f\u043e \u0441\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u044e'), (1, '\u041f\u0440\u043e\u043f\u0430\u0436\u0430 \u0438\u0437 \u0444\u043e\u043d\u0434\u043e\u0432 \u043e\u0442\u043a\u0440\u044b\u0442\u043e\u0433\u043e \u0434\u043e\u0441\u0442\u0443\u043f\u0430'), (2, '\u0423\u0442\u0435\u0440\u044f \u0447\u0438\u0442\u0430\u0442\u0435\u043b\u044f\u043c\u0438'), (3, '\u0425\u0438\u0449\u0435\u043d\u0438\u0435'), (4, '\u0411\u0435\u0434\u0441\u0442\u0432\u0438\u0435 \u0441\u0442\u0438\u0445\u0438\u0439\u043d\u043e\u0433\u043e \u0438 \u0442\u0435\u0445\u043d\u043e\u0433\u0435\u043d\u043d\u043e\u0433\u043e \u0445\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0430'), (5, '\u041f\u043e \u043d\u0435\u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043d\u044b\u043c \u043f\u0440\u0438\u0447\u0438\u043d\u0430\u043c (\u043d\u0435\u0434\u043e\u0441\u0442\u0430\u0447\u0430).'), (6, '\u0424\u0438\u0437\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0438\u0437\u043d\u043e\u0441'), (7, '\u041a\u043d\u0438\u0433\u043e\u043e\u0431\u043c\u0435\u043d \u0441 \u0434\u0440\u0443\u0433\u043e\u0439 \u0431\u0438\u0431\u043b\u0438\u043e\u0442\u0435\u043a\u043e\u0439'), (8, '\u0418\u043d\u043e\u0435'), (9, '\u0412\u044b\u0434\u0430\u043d\u043e \u0432 \u043e\u0431\u043c\u0435\u043d\u043d\u044b\u0439 \u0444\u043e\u043d\u0434'), (10, '\u041c\u043e\u0440\u0430\u043b\u044c\u043d\u044b\u0439 \u0438\u0437\u043d\u043e\u0441')], null=True, verbose_name='\u043f\u0440\u0438\u0447\u0438\u043d\u0430 \u0441\u043f\u0438\u0441\u0430\u043d\u0438\u044f'),
        ),
    ]
