# Generated by Django 2.2.28 on 2024-01-26 13:54

from django.db import (
    migrations,
)


def get_operations():
    from django.apps import (
        apps,
    )

    target_model = 'core.StudyLevel'

    try:
        apps.get_model(target_model)

    except LookupError:
        pass

    else:
        yield migrations.RemoveField(
            model_name='libregistryentry',
            name='study_levels',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lib_registry', '0037_auto_20240126_1337'),
    ]

    operations = list(get_operations())
