# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import pds.api_client
from pds.api_client.paths.products_identifier import get  # noqa: E501
from pds.api_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestProductsIdentifier(ApiTestMixin, unittest.TestCase):
    """
    ProductsIdentifier unit test stubs
        returns one PDS Product with the identifier selected from all PDS Products, including bundles, collections, data, documentation, context and observational products. See identifier for details on how it determines what is returned.   # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200
























if __name__ == '__main__':
    unittest.main()
