# Generated by Django 1.9.13 on 2018-04-20 09:41
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('lib_example_types', '0002_load_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryexampletype',
            name='external_id',
        ),
        migrations.AlterField(
            model_name='libraryexampletype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='libraryexampletype',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f'),
        ),
    ]
