import logging, io, os
global FILE_HANDLERS, LOG_RECORDS, WRITE_AT_EXIT, LOG_DATE_FORMAT, DEFAULT_HTML_THEME

FILE_HANDLERS = ()
WRITE_AT_EXIT = False
LOG_RECORDS = io.StringIO()
LOG_DATE_FORMAT = '%H:%M:%S'
DEFAULT_HTML_THEME = 'plain'

if 'TEXTTOOLS_HTML_DEFAULT_THEME' in os.environ:
    DEFAULT_HTML_THEME = os.environ['TEXTTOOLS_HTML_DEFAULT_THEME']
