from enum import Enum
class Kind(str,Enum):
    VAT = "vat",
    PROFORMA = "proforma"
    BILL = "bill"
    RECEIPT = "receipt"
    ADVANCE = "advance"
    FINAL = "final"
    CORRECTION = "correction"
    VAT_MP = "vat_mp"
    INVOICE_OTHER = "invoice_other"
    VAT_MARGIN = "vat_margin"
    KP = "kp"
    KW = "kw"
    ESTIMATE = "estimate"
    VAT_RR = "vat_rr"
    CORRECTION_NOTE = "correction_note"
    ACCOUNTING_NOTE = "accounting_note"
    CLIENT_ORDER = "client_order"
    DW = "dw"
    WNT = "wnt"
    WDT = "wdt"
    IMPORT_SERVICE = "import_service"
    IMPORT_SERVICE_EU = "import_service_eu"
    IMPORT_PRODUCTS = "import_products"
    EXPORT_PRODUCTS = "export_products"


class PaymentType(str,Enum):
    TRANSFER = "transfer"
    CARD = "card"
    CASH = "cash"
    BARTER = "barter"
    CHEQUE = "czek"
    BILL_OF_EXCHANGE = "bill_of_exchange"
    CASH_ON_DELIVERY = "cash_on_delivery"
    COMPENSATION = "compensation"
    LETTER_OF_CREDIT = "letter_of_credit"
    PAYU = "payu"
    PAYPAL = "paypal"
    OFF = "off"