import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('lib_passport', '0018_data_migration_for_work_mode_and_address'),
        ('schools', '0003_alter_school_territory_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libpassport',
            old_name='school_id',
            new_name='school',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='book_fund',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='documents_account',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='documents_legal',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='f_address_corps',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='f_address_full',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='f_address_house',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='f_address_house_guid',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='f_address_place',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='f_address_street',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='f_address_zipcode',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='inside_lib_work_from',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='inside_lib_work_to',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='is_abonement',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='is_access_internet',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='is_lib_store',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='is_media',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='is_pc_base',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='is_reading_room',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='lunch_hour_from',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='lunch_hour_to',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='main_fund',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='media_pc_cnt',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='mediafiles_audio',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='mediafiles_total',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='mediafiles_video',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='office_id',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='provided_services',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='reading_room_type',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='schoolbook_fund',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='shedule_fri_from',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='shedule_fri_to',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='shedule_mon_from',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='shedule_mon_to',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='shedule_sat_from',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='shedule_sat_to',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='shedule_sun_from',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='shedule_sun_to',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='shedule_thu_from',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='shedule_thu_to',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='shedule_tue_from',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='shedule_tue_to',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='shedule_wed_from',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='shedule_wed_to',
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='using_rules',
        ),
        migrations.AlterField(
            model_name='libpassport',
            name='date_found_month',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], null=True, verbose_name='Дата основания (месяц)'),
        ),
        migrations.AlterField(
            model_name='libpassport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='libpassport',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Наименование библиотеки'),
        ),
        migrations.AlterField(
            model_name='libpassport',
            name='school',
            field=models.OneToOneField(db_constraint=False, on_delete=models.DO_NOTHING, to='schools.School', verbose_name='Идентификатор ОО'),
        ),
        migrations.RemoveField(
            model_name='libpassport',
            name='cleanup_days_link',
        ),
    ]
