DATASETS_KEY = "datasets"
SKIPPABLE_TESTS_KEY = "skippable"
TEST_INTERNAL_DEPENDENCIES_KEY = "test-dependencies"

SKIPPABLE_GPU_KEY = "gpu"
SKIPPABLE_DEPENDENCIES_KEY = "dependencies"
SKIPPABLE_OTHERS_KEY = "others"

SKIPPABLE_DEPENDENCIES_NAME_KEY = "name"
SKIPPABLE_DEPENDENCIES_MODULE_KEY = "module"
SKIPPABLE_DEPENDENCIES_IS_PLUGIN_KEY = "isPlugin"
SKIPPABLE_DEPENDENCIES_TESTS_KEY = "tests"

SKIPPABLE_OTHERS_TEST_KEY = "test"
SKIPPABLE_OTHERS_REASON_KEY = "reason"
