
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-03T13:24:22+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f71713bfe3d8e96d7ca21588d3be6863673987d",
 "version": "1.8.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
