
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: llamazure/tf:llamazure.tf

from setuptools import setup

setup(**{
    'author': 'Daniel Goldman',
    'classifiers': [
        'Development Status :: 3 - Alpha',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.13',
        'Topic :: Utilities',
        'Topic :: Internet :: Log Analysis',
    ],
    'description': 'Generate some azurerm resources without the headache',
    'install_requires': (
    ),
    'license': 'Round Robin 2.0.0',
    'long_description': """# llamazure.tf

Easily generate azurerm resources.

## Network

Network rules are a pain. Generate them easily!
""",
    'long_description_content_type': 'text/markdown',
    'maintainer': 'Daniel Goldman',
    'name': 'llamazure.tf',
    'namespace_packages': (
    ),
    'package_data': {
    },
    'packages': (
        'llamazure.tf',
    ),
    'project_urls': {
        'Homepage': 'https://github.com/lilatomic/llamazure',
        'Repository': 'https://github.com/lilatomic/llamazure',
        'Changelog': 'https://github.com/lilatomic/llamazure/blob/main/llamazure/tf/changelog.md',
        'Issues': 'https://github.com/lilatomic/llamazure/issues',
    },
    'python_requires': '>=3.9',
    'version': '0.1.0',
})
