# Generated by Django 5.0.7 on 2024-08-09 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kriten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kritentask',
            name='kriten_cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kriten.kritencluster'),
        ),
    ]
