from _typeshed import Incomplete
from numpy.lib.shape_base import apply_along_axis as apply_along_axis, apply_over_axes as apply_over_axes, array_split as array_split, column_stack as column_stack, dsplit as dsplit, dstack as dstack, expand_dims as expand_dims, hsplit as hsplit, kron as kron, put_along_axis as put_along_axis, split as split, take_along_axis as take_along_axis, tile as tile, vsplit as vsplit
from numpy.testing import assert_ as assert_, assert_array_equal as assert_array_equal, assert_equal as assert_equal, assert_raises as assert_raises, assert_warns as assert_warns

IS_64BIT: Incomplete

class TestTakeAlongAxis:
    def test_argequivalent(self) -> None: ...
    def test_invalid(self) -> None: ...
    def test_empty(self) -> None: ...
    def test_broadcast(self) -> None: ...

class TestPutAlongAxis:
    def test_replace_max(self) -> None: ...
    def test_broadcast(self) -> None: ...

class TestApplyAlongAxis:
    def test_simple(self) -> None: ...
    def test_simple101(self) -> None: ...
    def test_3d(self) -> None: ...
    def test_preserve_subclass(self): ...
    def test_subclass(self): ...
    def test_scalar_array(self, cls=...) -> None: ...
    def test_0d_array(self, cls=...): ...
    def test_axis_insertion(self, cls=...): ...
    def test_subclass_preservation(self) -> None: ...
    def test_axis_insertion_ma(self): ...
    def test_tuple_func1d(self): ...
    def test_empty(self): ...
    def test_with_iterable_object(self): ...

class TestApplyOverAxes:
    def test_simple(self) -> None: ...

class TestExpandDims:
    def test_functionality(self) -> None: ...
    def test_axis_tuple(self) -> None: ...
    def test_axis_out_of_range(self) -> None: ...
    def test_repeated_axis(self) -> None: ...
    def test_subclasses(self) -> None: ...

class TestArraySplit:
    def test_integer_0_split(self) -> None: ...
    def test_integer_split(self) -> None: ...
    def test_integer_split_2D_rows(self) -> None: ...
    def test_integer_split_2D_cols(self) -> None: ...
    def test_integer_split_2D_default(self) -> None: ...
    def test_integer_split_2D_rows_greater_max_int32(self) -> None: ...
    def test_index_split_simple(self) -> None: ...
    def test_index_split_low_bound(self) -> None: ...
    def test_index_split_high_bound(self) -> None: ...

class TestSplit:
    def test_equal_split(self) -> None: ...
    def test_unequal_split(self) -> None: ...

class TestColumnStack:
    def test_non_iterable(self) -> None: ...
    def test_1D_arrays(self) -> None: ...
    def test_2D_arrays(self) -> None: ...
    def test_generator(self) -> None: ...

class TestDstack:
    def test_non_iterable(self) -> None: ...
    def test_0D_array(self) -> None: ...
    def test_1D_array(self) -> None: ...
    def test_2D_array(self) -> None: ...
    def test_2D_array2(self) -> None: ...
    def test_generator(self) -> None: ...

class TestHsplit:
    def test_non_iterable(self) -> None: ...
    def test_0D_array(self) -> None: ...
    def test_1D_array(self) -> None: ...
    def test_2D_array(self) -> None: ...

class TestVsplit:
    def test_non_iterable(self) -> None: ...
    def test_0D_array(self) -> None: ...
    def test_1D_array(self) -> None: ...
    def test_2D_array(self) -> None: ...

class TestDsplit:
    def test_non_iterable(self) -> None: ...
    def test_0D_array(self) -> None: ...
    def test_1D_array(self) -> None: ...
    def test_2D_array(self) -> None: ...
    def test_3D_array(self) -> None: ...

class TestSqueeze:
    def test_basic(self) -> None: ...

class TestKron:
    def test_return_type(self) -> None: ...
    def test_kron_smoke(self, array_class) -> None: ...
    def test_kron_ma(self) -> None: ...
    def test_kron_shape(self, shape_a, shape_b) -> None: ...

class TestTile:
    def test_basic(self) -> None: ...
    def test_tile_one_repetition_on_array_gh4679(self) -> None: ...
    def test_empty(self) -> None: ...
    def test_kroncompare(self) -> None: ...

class TestMayShareMemory:
    def test_basic(self) -> None: ...

def compare_results(res, desired) -> None: ...
