from _typeshed import Incomplete
from numpy.testing import assert_ as assert_, assert_allclose as assert_allclose, assert_almost_equal as assert_almost_equal, assert_array_almost_equal as assert_array_almost_equal, assert_array_equal as assert_array_equal, assert_equal as assert_equal, assert_raises as assert_raises

TYPE_CODES: Incomplete

class TestPolynomial:
    def test_poly1d_str_and_repr(self) -> None: ...
    def test_poly1d_resolution(self) -> None: ...
    def test_poly1d_math(self) -> None: ...
    def test_poly1d_misc(self, type_code: str) -> None: ...
    def test_poly1d_variable_arg(self) -> None: ...
    def test_poly(self) -> None: ...
    def test_roots(self) -> None: ...
    def test_str_leading_zeros(self) -> None: ...
    def test_polyfit(self) -> None: ...
    def test_objects(self) -> None: ...
    def test_complex(self) -> None: ...
    def test_integ_coeffs(self) -> None: ...
    def test_zero_dims(self) -> None: ...
    def test_poly_int_overflow(self) -> None: ...
    def test_zero_poly_dtype(self) -> None: ...
    def test_poly_eq(self) -> None: ...
    def test_polydiv(self) -> None: ...
    def test_poly_coeffs_mutable(self) -> None: ...
