from numpy.lib.index_tricks import diag_indices as diag_indices, diag_indices_from as diag_indices_from, fill_diagonal as fill_diagonal, index_exp as index_exp, ix_ as ix_, mgrid as mgrid, ndenumerate as ndenumerate, ndindex as ndindex, ogrid as ogrid, r_ as r_, s_ as s_
from numpy.testing import assert_ as assert_, assert_almost_equal as assert_almost_equal, assert_array_almost_equal as assert_array_almost_equal, assert_array_equal as assert_array_equal, assert_equal as assert_equal, assert_raises as assert_raises, assert_raises_regex as assert_raises_regex

class TestRavelUnravelIndex:
    def test_basic(self) -> None: ...
    def test_empty_indices(self) -> None: ...
    def test_big_indices(self) -> None: ...
    def test_dtypes(self) -> None: ...
    def test_clipmodes(self) -> None: ...
    def test_writeability(self) -> None: ...
    def test_0d(self) -> None: ...
    def test_empty_array_ravel(self, mode) -> None: ...
    def test_empty_array_unravel(self) -> None: ...

class TestGrid:
    def test_basic(self) -> None: ...
    def test_linspace_equivalence(self) -> None: ...
    def test_nd(self) -> None: ...
    def test_sparse(self) -> None: ...
    def test_mgrid_size_none_handling(self, start, stop, step, expected) -> None: ...
    def test_accepts_npfloating(self) -> None: ...
    def test_accepts_npcomplexfloating(self) -> None: ...

class TestConcatenator:
    def test_1d(self) -> None: ...
    def test_mixed_type(self) -> None: ...
    def test_more_mixed_type(self) -> None: ...
    def test_complex_step(self) -> None: ...
    def test_2d(self) -> None: ...
    def test_0d(self) -> None: ...

class TestNdenumerate:
    def test_basic(self) -> None: ...

class TestIndexExpression:
    def test_regression_1(self) -> None: ...
    def test_simple_1(self) -> None: ...

class TestIx_:
    def test_regression_1(self) -> None: ...
    def test_shape_and_dtype(self) -> None: ...
    def test_bool(self) -> None: ...
    def test_1d_only(self) -> None: ...
    def test_repeated_input(self) -> None: ...

def test_c_() -> None: ...

class TestFillDiagonal:
    def test_basic(self) -> None: ...
    def test_tall_matrix(self) -> None: ...
    def test_tall_matrix_wrap(self) -> None: ...
    def test_wide_matrix(self) -> None: ...
    def test_operate_4d_array(self) -> None: ...
    def test_low_dim_handling(self) -> None: ...
    def test_hetero_shape_handling(self) -> None: ...

def test_diag_indices() -> None: ...

class TestDiagIndicesFrom:
    def test_diag_indices_from(self) -> None: ...
    def test_error_small_input(self) -> None: ...
    def test_error_shape_mismatch(self) -> None: ...

def test_ndindex() -> None: ...
