# Generated by Django 1.11.25 on 2019-10-21 13:32
from django.db import (
    migrations,
)


class Migration(migrations.Migration):

    dependencies = [
        ('lib_udc', '0004_libraryudc_index_udc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryudc',
            options={
                'verbose_name': '\u0420\u0430\u0437\u0434\u0435\u043b \u0423\u0414\u041a',
                'verbose_name_plural': '\u0420\u0430\u0437\u0434\u0435\u043b\u044b \u0423\u0414\u041a'
            },
        ),
    ]
