import os

# GITLAB
GITLAB_API_VERSION = os.environ.get("GITLAB_API_VERSION", "https://gitlab.com/api/v4")
GITLAB_PAGINATION_PER_PAGE = int(os.environ.get("GITLAB_PAGINATION_PER_PAGE", 100))
GITLAB_PROJECT_SIMPLE = os.environ.get("GITLAB_PROJECT_SIMPLE", True)
GITLAB_PROJECT_PERSONAL_ONLY = os.environ.get("GITLAB_PROJECT_PERSONAL_ONLY", False)
GITLAB_PROJECT_USER_ACCESS = int(os.environ.get("GITLAB_PROJECT_USER_ACCESS", 40))
GITLAB_PROJECT_USER_MEMBERSHIP = os.environ.get("GITLAB_PROJECT_USER_MEMBERSHIP", None)
GITLAB_PROJECT_VISIBILITY = os.environ.get("GITLAB_PROJECT_VISIBILITY", "public")
GITLAB_TOKEN = os.environ.get("GITLAB_TOKEN", None)

# TIME
DATE_ISO_8601 = "%Y-%m-%d"
DATE_ISO_8601_TIME = "%Y-%m-%dT%H:%M:%S.%fZ"
