# Generated by Django 1.11.18 on 2019-03-11 08:25
import django.db.models.deletion
from django.db import (
    migrations,
    models,
)

import edulib.core.base.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
                ('name', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('filename', models.FileField(max_length=255, upload_to=edulib.core.base.files.upload_named_handler, verbose_name='\u0424\u0430\u0439\u043b')),
                ('school', models.BigIntegerField(verbose_name='\u0428\u043a\u043e\u043b\u0430')),
            ],
            options={
                'db_table': 'library_scanned_copy',
                'verbose_name': '\u0421\u043a\u0430\u043d-\u043a\u043e\u043f\u0438\u044f',
                'verbose_name_plural': '\u0421\u043a\u0430\u043d-\u043a\u043e\u043f\u0438\u0438',
            },
        ),
    ]
