
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-04T20:47:39+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4b0da04c356b4bcf638e3eccfdecf3ee3b50247",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
