# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resemble/v1alpha1/react.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dresemble/v1alpha1/react.proto\x12\x11resemble.v1alpha1\x1a\x1cgoogle/api/annotations.proto\"/\n\x0cQueryRequest\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0f\n\x07request\x18\x02 \x01(\x0c\"M\n\rQueryResponse\x12\x15\n\x08response\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\x18\n\x10idempotency_keys\x18\x02 \x03(\tB\x0b\n\t_response\"u\n\rMutateRequest\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0f\n\x07request\x18\x02 \x01(\x0c\x12\x17\n\x0fidempotency_key\x18\x03 \x01(\t\x12\x19\n\x0c\x62\x65\x61rer_token\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_bearer_token\"L\n\x0eMutateResponse\x12\x12\n\x08response\x18\x01 \x01(\x0cH\x00\x12\x10\n\x06status\x18\x02 \x01(\tH\x00\x42\x14\n\x12response_or_status\"\x1d\n\x1bWebSocketsConnectionRequest\"\x1e\n\x1cWebSocketsConnectionResponse2\xae\x02\n\x05React\x12t\n\x05Query\x12\x1f.resemble.v1alpha1.QueryRequest\x1a .resemble.v1alpha1.QueryResponse\"&\x82\xd3\xe4\x93\x02 \"\x1e/resemble.v1alpha1.React/Query0\x01\x12\xae\x01\n\x14WebSocketsConnection\x12..resemble.v1alpha1.WebSocketsConnectionRequest\x1a/.resemble.v1alpha1.WebSocketsConnectionResponse\"5\x82\xd3\xe4\x93\x02/\"-/resemble.v1alpha1.React/WebSocketsConnectionb\x06proto3')



_QUERYREQUEST = DESCRIPTOR.message_types_by_name['QueryRequest']
_QUERYRESPONSE = DESCRIPTOR.message_types_by_name['QueryResponse']
_MUTATEREQUEST = DESCRIPTOR.message_types_by_name['MutateRequest']
_MUTATERESPONSE = DESCRIPTOR.message_types_by_name['MutateResponse']
_WEBSOCKETSCONNECTIONREQUEST = DESCRIPTOR.message_types_by_name['WebSocketsConnectionRequest']
_WEBSOCKETSCONNECTIONRESPONSE = DESCRIPTOR.message_types_by_name['WebSocketsConnectionResponse']
QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYREQUEST,
  '__module__' : 'resemble.v1alpha1.react_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.QueryRequest)
  })
_sym_db.RegisterMessage(QueryRequest)

QueryResponse = _reflection.GeneratedProtocolMessageType('QueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYRESPONSE,
  '__module__' : 'resemble.v1alpha1.react_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.QueryResponse)
  })
_sym_db.RegisterMessage(QueryResponse)

MutateRequest = _reflection.GeneratedProtocolMessageType('MutateRequest', (_message.Message,), {
  'DESCRIPTOR' : _MUTATEREQUEST,
  '__module__' : 'resemble.v1alpha1.react_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.MutateRequest)
  })
_sym_db.RegisterMessage(MutateRequest)

MutateResponse = _reflection.GeneratedProtocolMessageType('MutateResponse', (_message.Message,), {
  'DESCRIPTOR' : _MUTATERESPONSE,
  '__module__' : 'resemble.v1alpha1.react_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.MutateResponse)
  })
_sym_db.RegisterMessage(MutateResponse)

WebSocketsConnectionRequest = _reflection.GeneratedProtocolMessageType('WebSocketsConnectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _WEBSOCKETSCONNECTIONREQUEST,
  '__module__' : 'resemble.v1alpha1.react_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.WebSocketsConnectionRequest)
  })
_sym_db.RegisterMessage(WebSocketsConnectionRequest)

WebSocketsConnectionResponse = _reflection.GeneratedProtocolMessageType('WebSocketsConnectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _WEBSOCKETSCONNECTIONRESPONSE,
  '__module__' : 'resemble.v1alpha1.react_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.WebSocketsConnectionResponse)
  })
_sym_db.RegisterMessage(WebSocketsConnectionResponse)

_REACT = DESCRIPTOR.services_by_name['React']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REACT.methods_by_name['Query']._options = None
  _REACT.methods_by_name['Query']._serialized_options = b'\202\323\344\223\002 \"\036/resemble.v1alpha1.React/Query'
  _REACT.methods_by_name['WebSocketsConnection']._options = None
  _REACT.methods_by_name['WebSocketsConnection']._serialized_options = b'\202\323\344\223\002/\"-/resemble.v1alpha1.React/WebSocketsConnection'
  _QUERYREQUEST._serialized_start=82
  _QUERYREQUEST._serialized_end=129
  _QUERYRESPONSE._serialized_start=131
  _QUERYRESPONSE._serialized_end=208
  _MUTATEREQUEST._serialized_start=210
  _MUTATEREQUEST._serialized_end=327
  _MUTATERESPONSE._serialized_start=329
  _MUTATERESPONSE._serialized_end=405
  _WEBSOCKETSCONNECTIONREQUEST._serialized_start=407
  _WEBSOCKETSCONNECTIONREQUEST._serialized_end=436
  _WEBSOCKETSCONNECTIONRESPONSE._serialized_start=438
  _WEBSOCKETSCONNECTIONRESPONSE._serialized_end=468
  _REACT._serialized_start=471
  _REACT._serialized_end=773
# @@protoc_insertion_point(module_scope)
