# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import picture_pb2 as picture__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in picture_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PictureServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.unary_unary(
                '/batchx.cdn.PictureService/Upload',
                request_serializer=picture__pb2.UploadRequest.SerializeToString,
                response_deserializer=picture__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.UploadPresigned = channel.unary_unary(
                '/batchx.cdn.PictureService/UploadPresigned',
                request_serializer=picture__pb2.UploadPresignedRequest.SerializeToString,
                response_deserializer=picture__pb2.UploadPresignedResponse.FromString,
                _registered_method=True)
        self.CompleteUpload = channel.unary_unary(
                '/batchx.cdn.PictureService/CompleteUpload',
                request_serializer=picture__pb2.CompleteUploadRequest.SerializeToString,
                response_deserializer=picture__pb2.CompleteUploadResponse.FromString,
                _registered_method=True)
        self.CropPicture = channel.unary_unary(
                '/batchx.cdn.PictureService/CropPicture',
                request_serializer=picture__pb2.CropPictureRequest.SerializeToString,
                response_deserializer=picture__pb2.CropPictureResponse.FromString,
                _registered_method=True)


class PictureServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Upload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadPresigned(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CropPicture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PictureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upload': grpc.unary_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=picture__pb2.UploadRequest.FromString,
                    response_serializer=picture__pb2.UploadResponse.SerializeToString,
            ),
            'UploadPresigned': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadPresigned,
                    request_deserializer=picture__pb2.UploadPresignedRequest.FromString,
                    response_serializer=picture__pb2.UploadPresignedResponse.SerializeToString,
            ),
            'CompleteUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteUpload,
                    request_deserializer=picture__pb2.CompleteUploadRequest.FromString,
                    response_serializer=picture__pb2.CompleteUploadResponse.SerializeToString,
            ),
            'CropPicture': grpc.unary_unary_rpc_method_handler(
                    servicer.CropPicture,
                    request_deserializer=picture__pb2.CropPictureRequest.FromString,
                    response_serializer=picture__pb2.CropPictureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'batchx.cdn.PictureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('batchx.cdn.PictureService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PictureService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Upload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batchx.cdn.PictureService/Upload',
            picture__pb2.UploadRequest.SerializeToString,
            picture__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadPresigned(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batchx.cdn.PictureService/UploadPresigned',
            picture__pb2.UploadPresignedRequest.SerializeToString,
            picture__pb2.UploadPresignedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batchx.cdn.PictureService/CompleteUpload',
            picture__pb2.CompleteUploadRequest.SerializeToString,
            picture__pb2.CompleteUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CropPicture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/batchx.cdn.PictureService/CropPicture',
            picture__pb2.CropPictureRequest.SerializeToString,
            picture__pb2.CropPictureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
