# Generated by Django 4.2.4 on 2023-11-30 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_sensors", "0002_deviceconfiguration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensor",
            name="description",
        ),
    ]
