# Generated by Django 1.9.13 on 2018-06-22 11:04
from django.db import (
    migrations,
)


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0005_auto_20180420_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrequesthistory',
            name='subject_id',
        ),
    ]
