# Generated by Django 2.2.28 on 2024-02-02 09:06

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0012_auto_20220112_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequesthistory',
            name='parent',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Родитель'),
        ),
    ]
