# Generated by Django 5.0.3 on 2024-08-22 09:33

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('lib_example_types', '0006_remove_libraryexampletype_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryexampletype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='libraryexampletype',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Наименование'),
        ),
    ]
