# Generated by Django 1.11.18 on 2019-01-24 07:06
from django.db import (
    migrations,
    models,
)


def get_operations():
    from django.apps import (
        apps,
    )

    target_model = 'core.StudyLevel'

    try:
        apps.get_model(target_model)

    except LookupError:
        pass

    else:
        yield migrations.AddField(
            model_name='libregistryentry',
            name='study_levels',
            field=models.ManyToManyField(
                to=target_model,
                verbose_name='\u0423\u0440\u043e\u0432\u043d\u0438 \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f'
            ),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lib_registry', '0011_auto_20181206_0712'),
    ]

    operations = list(get_operations())
