"""Миграции."""
# Generated by Django 1.11.29 on 2021-01-11 13:21
import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    """Миграция."""

    dependencies = [
        ('lib_registry', '0027_libsummarybook_upto_11'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibSummaryBookCalculated',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('created', models.DateTimeField(
                    auto_now_add=True,
                    null=True,
                    verbose_name='Дата создания'
                )),
                ('modified', models.DateTimeField(
                    auto_now=True,
                    null=True,
                    verbose_name='Дата изменения'
                )),
                ('calculated', models.BooleanField(
                    default=False,
                    verbose_name='Расчёт выполнен'
                )),
                ('note', models.CharField(
                    blank=True,
                    max_length=256,
                    null=True,
                    verbose_name='Примечание'
                )),
                ('school', models.BigIntegerField(
                    verbose_name='Школа'
                )),
            ],
            options={
                'db_table': 'lib_summary_book_calculated',
                'verbose_name': 'Вычисленная КСУ',
                'verbose_name_plural': 'Вычисленные КСУ',
            },
        ),
    ]
