# Generated by Django 2.2.28 on 2024-02-05 12:01

from django.db import (
    migrations,
)


class Migration(migrations.Migration):

    dependencies = [
        ('lib_registry', '0039_auto_20240205_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libexchangefund',
            old_name='teacher',
            new_name='teacher_id',
        ),
    ]
