from _typeshed import Incomplete
from numpy.testing import assert_ as assert_, assert_equal as assert_equal, assert_raises as assert_raises

def urlopen_stub(url, data: Incomplete | None = None): ...

old_urlopen: Incomplete

def setup_module() -> None: ...
def teardown_module() -> None: ...

http_path: str
http_file: str
http_fakepath: str
http_fakefile: str
malicious_files: Incomplete
magic_line: bytes

def valid_textfile(filedir): ...
def invalid_textfile(filedir): ...
def valid_httpurl(): ...
def invalid_httpurl(): ...
def valid_baseurl(): ...
def invalid_baseurl(): ...
def valid_httpfile(): ...
def invalid_httpfile(): ...

class TestDataSourceOpen:
    tmpdir: Incomplete
    ds: Incomplete
    def setup_method(self) -> None: ...
    def teardown_method(self) -> None: ...
    def test_ValidHTTP(self) -> None: ...
    def test_InvalidHTTP(self) -> None: ...
    def test_InvalidHTTPCacheURLError(self) -> None: ...
    def test_ValidFile(self) -> None: ...
    def test_InvalidFile(self) -> None: ...
    def test_ValidGzipFile(self) -> None: ...
    def test_ValidBz2File(self) -> None: ...

class TestDataSourceExists:
    tmpdir: Incomplete
    ds: Incomplete
    def setup_method(self) -> None: ...
    def teardown_method(self) -> None: ...
    def test_ValidHTTP(self) -> None: ...
    def test_InvalidHTTP(self) -> None: ...
    def test_ValidFile(self) -> None: ...
    def test_InvalidFile(self) -> None: ...

class TestDataSourceAbspath:
    tmpdir: Incomplete
    ds: Incomplete
    def setup_method(self) -> None: ...
    def teardown_method(self) -> None: ...
    def test_ValidHTTP(self) -> None: ...
    def test_ValidFile(self) -> None: ...
    def test_InvalidHTTP(self) -> None: ...
    def test_InvalidFile(self) -> None: ...
    def test_sandboxing(self): ...
    def test_windows_os_sep(self) -> None: ...

class TestRepositoryAbspath:
    tmpdir: Incomplete
    repos: Incomplete
    def setup_method(self) -> None: ...
    def teardown_method(self) -> None: ...
    def test_ValidHTTP(self) -> None: ...
    def test_sandboxing(self): ...
    def test_windows_os_sep(self) -> None: ...

class TestRepositoryExists:
    tmpdir: Incomplete
    repos: Incomplete
    def setup_method(self) -> None: ...
    def teardown_method(self) -> None: ...
    def test_ValidFile(self) -> None: ...
    def test_InvalidFile(self) -> None: ...
    def test_RemoveHTTPFile(self) -> None: ...
    def test_CachedHTTPFile(self) -> None: ...

class TestOpenFunc:
    tmpdir: Incomplete
    def setup_method(self) -> None: ...
    def teardown_method(self) -> None: ...
    def test_DataSourceOpen(self) -> None: ...

def test_del_attr_handling() -> None: ...
