from _typeshed import Incomplete
from io import BytesIO
from numpy.lib import format as format
from numpy.testing import IS_PYPY as IS_PYPY, assert_ as assert_, assert_array_equal as assert_array_equal, assert_raises as assert_raises, assert_raises_regex as assert_raises_regex, assert_warns as assert_warns
from numpy.testing._private.utils import requires_memory as requires_memory

scalars: Incomplete
basic_arrays: Incomplete
dtype: Incomplete
basic: Incomplete
Pdescr: Incomplete
PbufferT: Incomplete
Ndescr: Incomplete
NbufferT: Incomplete
record_arrays: Incomplete

class BytesIOSRandomSize(BytesIO):
    def read(self, size: Incomplete | None = None): ...

def roundtrip(arr): ...
def roundtrip_randsize(arr): ...
def roundtrip_truncated(arr): ...
def assert_equal_(o1, o2) -> None: ...
def test_roundtrip() -> None: ...
def test_roundtrip_randsize() -> None: ...
def test_roundtrip_truncated() -> None: ...
def test_long_str() -> None: ...
def test_memmap_roundtrip(tmpdir) -> None: ...
def test_compressed_roundtrip(tmpdir) -> None: ...

dt1: Incomplete
dt2: Incomplete
dt3: Incomplete
dt4: Incomplete
dt5: Incomplete
dt6: Incomplete

def test_load_padded_dtype(tmpdir, dt) -> None: ...
def test_python2_python3_interoperability() -> None: ...
def test_pickle_python2_python3() -> None: ...
def test_pickle_disallow(tmpdir) -> None: ...
def test_descr_to_dtype(dt) -> None: ...
def test_version_2_0() -> None: ...
def test_version_2_0_memmap(tmpdir) -> None: ...
def test_huge_header(tmpdir, mmap_mode) -> None: ...
def test_huge_header_npz(tmpdir) -> None: ...
def test_write_version() -> None: ...

bad_version_magic: Incomplete
malformed_magic: Incomplete

def test_read_magic() -> None: ...
def test_read_magic_bad_magic() -> None: ...
def test_read_version_1_0_bad_magic() -> None: ...
def test_bad_magic_args() -> None: ...
def test_large_header() -> None: ...
def test_read_array_header_1_0() -> None: ...
def test_read_array_header_2_0() -> None: ...
def test_bad_header() -> None: ...
def test_large_file_support(tmpdir) -> None: ...
def test_large_archive(tmpdir) -> None: ...
def test_empty_npz(tmpdir) -> None: ...
def test_unicode_field_names(tmpdir) -> None: ...
def test_metadata_dtype(dt, fail) -> None: ...
