from _typeshed import Incomplete
from numpy.core import arange as arange
from numpy.lib import deprecate as deprecate, deprecate_with_doc as deprecate_with_doc
from numpy.testing import assert_ as assert_, assert_equal as assert_equal, assert_raises_regex as assert_raises_regex

def test_lookfor() -> None: ...
def old_func(self, x): ...
def old_func2(self, x): ...
def old_func3(self, x): ...

new_func3: Incomplete

def old_func4(self, x): ...

new_func4: Incomplete

def old_func5(self, x): ...

new_func5: Incomplete

def old_func6(self, x): ...

new_func6: Incomplete

def old_func7(self, x): ...
def test_deprecate_decorator() -> None: ...
def test_deprecate_decorator_message() -> None: ...
def test_deprecate_fn() -> None: ...
def test_deprecate_with_doc_decorator_message() -> None: ...
def test_deprecate_help_indentation(old_func, new_func) -> None: ...
def test_deprecate_preserve_whitespace() -> None: ...
def test_safe_eval_nameconstant() -> None: ...

class TestByteBounds:
    def test_byte_bounds(self) -> None: ...
    def test_unusual_order_positive_stride(self) -> None: ...
    def test_unusual_order_negative_stride(self) -> None: ...
    def test_strided(self) -> None: ...

def test_assert_raises_regex_context_manager() -> None: ...
def test_info_method_heading(): ...
