from numpy.lib import NumpyVersion as NumpyVersion
from numpy.testing import assert_ as assert_, assert_raises as assert_raises

def test_main_versions() -> None: ...
def test_version_1_point_10() -> None: ...
def test_alpha_beta_rc() -> None: ...
def test_dev_version() -> None: ...
def test_dev_a_b_rc_mixed() -> None: ...
def test_dev0_version() -> None: ...
def test_dev0_a_b_rc_mixed() -> None: ...
def test_raises() -> None: ...
