from _typeshed import Incomplete
from numpy.testing import assert_ as assert_, assert_array_equal as assert_array_equal, assert_equal as assert_equal, assert_raises as assert_raises, assert_warns as assert_warns

class TestUfunclike:
    def test_isposinf(self) -> None: ...
    def test_isneginf(self) -> None: ...
    def test_fix(self) -> None: ...
    metadata: Incomplete
    def test_fix_with_subclass(self): ...
    def test_deprecated(self) -> None: ...
    def test_scalar(self) -> None: ...
