ARTISTS = [
    # 'kyogoku_shin',
    # 'saw272',
    # 'wulie_errr',
    # 'yksb_inc6',
    # 'k00s',
    # 'hyulla',
    # 'mygiorni',
    # 'qi==qi',
    # 'labombardier!',
    # 'kb-mon',
    # 'nikichen',
    # 'kaguura_(kagu)',
    # 'nyantcha',
    # 'tandem',
    # 'lilithbloody',
    # 'komura_hiroto',
    # 'ciloranko',
    # 'sho_(sho_lwlw)',
    # 'manatsuki_manata',
    # 'nanaken_nana',
    # 'unrefle',
    # 'aimitkkays',
    # 'shiqicheng',
    # 'mian_lang',
    # 'btmr_game',
    # 'erupusai2',
    # 'k00s',
    # 'lucaxu1991',
    # 'kidkuroba4869',
    # 'ayanon_ite',
    # 'kyuuba_melo',
    # 'deltapork',
    # 'neorarty',
    # 'biiko_(king1015g)',
    # 'cofffee',
    # 'luxearte',
    # 'shiraki_(shiraki_shiki)',
    # 'mayuakakun',
    # 'riko-m',
    # 'deltapork',
    # 'blackbox_(blackbox9158)',
    # 'emmmerald',
    # 'alpha-type'

    # 'thundergotch',
    # 'mitsuki3s_kir',
    # 'rakeemspoon',
    # 'akuta_vi',
    # 'limart',
    # 'uniki_niki_niki',
    # 'kuno_(runkunochan)',
    # 'zeniyan',
    # 'yoshinari_you',
    # 'ata-zhubo',
    # 'feihuanjiang',
    # 'nia_(nia4294)',
    # 'frankie_foster',
    # 'buttercup_(ppg)',
    # 'sovetsky_soyuz_(azur_lane)',
    # 'sydus',
    # 'beeeeen',
    # 'mont_blanca',
    # 'mura_karuki',
    # 'majamari',
    # 'neg_(101neg)',
    # 'cessa',
    # 'hominamia',
    # 'aoi_suzu',
    # 'badluck2033',
    # 'ask_(askzy)',
    # 'kinutani_yutaka',
    # 'ms_tsukii',
    # 'shinkai_makoto',
    # 'studio_ghibli',
    # 'umehara_sei',
    # 'hisen_kaede',
    # 'ibuo_(ibukht1015)',
    # 'zenmaibook',
    # 'romiy',
    # 'deathalice',
    # 'yanderenasa',
    # 'tsuyukusa_(eeta7273)',
    # 'redum4',
    # 'skn',
    # 'kanashi_kumo',
    # 'nagu',
    # 'meola',
    # 'tommer',
    # 'wonbin_lee',
    # 'inu_totemo',
    # 'housou-kun',
    # 'z3zz4',
    # 'noir_(ibaraki)',
    # 'alice_vu',
    # 'junny',

    # 'segami',
    # 'yoshicha',
    # 'ravine_bells',
    # 'ttk_(kirinottk)',
    # 'heqing',
    # 'jung_wonjo',
    # 'kaiser_(kaiserofart)',
    # 'u_u_zan',
    # 'soono_(rlagpfl)',
    # 'all_nobori',
    # 'mery_(yangmalgage)',
    # 'nik_ibi',
    # 'spirit_chiasma',
    # 'asteroid_ill',
    # 'soleil_(soleilmtfbwy03)',
    # 'some1else45',
    # 'matsuura_kento',
    # 'dino_(dinoartforame)',
    # 'bob_(bobtheneet)',
    # 'hungry_clicker',
    # '333_(dqqqdle)',
    # 'shiokonbu',
    # 'wigfire',
    # 'harano_kaguyama',
    # 'hohehohe',
    # 'betabeet',
    # 'minami_(minami373916)',
    # 'riko_(rik0ring)',
    # 'po_(anhk5528)',
    # 'motoharu_(motoharuuuu)',
    # 'cro_(user_znms5733)',
    # 'haruyama_kazunori',
    # 'ogura_tubuan',
    # 'rity',
    # 'kji_(rozo)',
    # 'kamikiririp',
    # 'senzzang',
    # 'shake_0607',
    # 'i!roha',
    # 'bkub',
    # 'tony_taka',
    # 'matsunaga_kouyou',
    # 'blade_(galaxist)',
    # 'a1_(initial-g)',
    # 'bow_(bhp)',
    # 'ojipon',
    # 'bb_(baalbuddy)',
    # 'hisahiko',
    # 'rebecca_(keinelove)',
    # 'qvlv_kuzi_feichuan',
    # 'dd_(ijigendd)',
    # 'john_kafka',
    # 'hungry_clicker',
    # 'carnelian',
    # 'huhi_(huhi_1211)',
    # 'rakugaki_shiho',
    # 'temmie_chang',
    # 'lycanthix',
    # 'kimura_731',
    # 'rnaro_maro',
    # 'minusk9',
    # 'luna_(luna610)',
    # 'quasarcake',
    # 'megateru',

    'soosaresu',
    'kuuron_(moesann17)',
    'sasha_khmel',
    'dsmile',
    'huangdanlan',
    'mikafen',
    'otimusyairoha',
    'mallllma',
    'www_planet',
    'tf_cafe',
    'vamjulian',
    'o0oherb',
    'yasua_5',
    'ryota-h',
    'tama_launcher',
    'rider_(orange_couture)',
    'kurage20001',
    'ryohei_29',
    'ashiomi_masato',
    'nanoka_san',
    'nakai_(nnnjpg)',
    'ebi_draw',
    'shioajiass',
    'archinoer',
    'inushima',
    'matatabeat',
    'yuukami_(wittsu)',
    'himemura_saki',
    'isshiki_(ffmania7)',
    'o0oherb',
    'imai_takahiro',
    'cinderone',
    'kazane-wind',
    'houkisei',
    'taiki',
    'sushispin',
    'leebo_(leeboxxx)',
    'kein_v',
    'tugmix',
]
