from amsdal_data.connections.manager import ConnectionsManager as ConnectionsManager
from amsdal_data.operations.manager import OperationsManagerBase as OperationsManagerBase
from amsdal_data.transactions.manager import AmsdalTransactionManager as AmsdalTransactionManager
from amsdal_utils.utils.singleton import Singleton

class AmsdalDataManager(metaclass=Singleton):
    _connection_manager: ConnectionsManager
    _transaction_manager: AmsdalTransactionManager
    _operations_manager: OperationsManagerBase
    def set_connection_manager(self, connection_manager: ConnectionsManager) -> None: ...
    def set_operations_manager(self, operations_manager: OperationsManagerBase) -> None: ...
    def get_operations_manager(self) -> OperationsManagerBase: ...
    def get_connection_manager(self) -> ConnectionsManager: ...
    def get_transaction_manager(self) -> AmsdalTransactionManager: ...
