# coding: utf-8

"""
    UiPath.WebApi 18.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 18.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from uipath_orchestrator_rest.configuration import Configuration


class ActivitySettingsDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'api_version': 'str',
        'signal_r': 'SignalRActivitySettingsDto'
    }

    attribute_map = {
        'api_version': 'ApiVersion',
        'signal_r': 'SignalR'
    }

    def __init__(self, api_version=None, signal_r=None, _configuration=None):  # noqa: E501
        """ActivitySettingsDto - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._api_version = None
        self._signal_r = None
        self.discriminator = None

        if api_version is not None:
            self.api_version = api_version
        if signal_r is not None:
            self.signal_r = signal_r

    @property
    def api_version(self):
        """Gets the api_version of this ActivitySettingsDto.  # noqa: E501

        Current Orchestrator api version  # noqa: E501

        :return: The api_version of this ActivitySettingsDto.  # noqa: E501
        :rtype: str
        """
        return self._api_version

    @api_version.setter
    def api_version(self, api_version):
        """Sets the api_version of this ActivitySettingsDto.

        Current Orchestrator api version  # noqa: E501

        :param api_version: The api_version of this ActivitySettingsDto.  # noqa: E501
        :type: str
        """

        self._api_version = api_version

    @property
    def signal_r(self):
        """Gets the signal_r of this ActivitySettingsDto.  # noqa: E501


        :return: The signal_r of this ActivitySettingsDto.  # noqa: E501
        :rtype: SignalRActivitySettingsDto
        """
        return self._signal_r

    @signal_r.setter
    def signal_r(self, signal_r):
        """Sets the signal_r of this ActivitySettingsDto.


        :param signal_r: The signal_r of this ActivitySettingsDto.  # noqa: E501
        :type: SignalRActivitySettingsDto
        """

        self._signal_r = signal_r

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActivitySettingsDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActivitySettingsDto):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ActivitySettingsDto):
            return True

        return self.to_dict() != other.to_dict()
