# coding: utf-8

"""
    UiPath.WebApi 18.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 18.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from uipath_orchestrator_rest.configuration import Configuration


class SetUsersRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'added_user_ids': 'list[int]',
        'removed_user_ids': 'list[int]'
    }

    attribute_map = {
        'added_user_ids': 'addedUserIds',
        'removed_user_ids': 'removedUserIds'
    }

    def __init__(self, added_user_ids=None, removed_user_ids=None, _configuration=None):  # noqa: E501
        """SetUsersRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._added_user_ids = None
        self._removed_user_ids = None
        self.discriminator = None

        self.added_user_ids = added_user_ids
        self.removed_user_ids = removed_user_ids

    @property
    def added_user_ids(self):
        """Gets the added_user_ids of this SetUsersRequest.  # noqa: E501


        :return: The added_user_ids of this SetUsersRequest.  # noqa: E501
        :rtype: list[int]
        """
        return self._added_user_ids

    @added_user_ids.setter
    def added_user_ids(self, added_user_ids):
        """Sets the added_user_ids of this SetUsersRequest.


        :param added_user_ids: The added_user_ids of this SetUsersRequest.  # noqa: E501
        :type: list[int]
        """
        if self._configuration.client_side_validation and added_user_ids is None:
            raise ValueError("Invalid value for `added_user_ids`, must not be `None`")  # noqa: E501

        self._added_user_ids = added_user_ids

    @property
    def removed_user_ids(self):
        """Gets the removed_user_ids of this SetUsersRequest.  # noqa: E501


        :return: The removed_user_ids of this SetUsersRequest.  # noqa: E501
        :rtype: list[int]
        """
        return self._removed_user_ids

    @removed_user_ids.setter
    def removed_user_ids(self, removed_user_ids):
        """Sets the removed_user_ids of this SetUsersRequest.


        :param removed_user_ids: The removed_user_ids of this SetUsersRequest.  # noqa: E501
        :type: list[int]
        """
        if self._configuration.client_side_validation and removed_user_ids is None:
            raise ValueError("Invalid value for `removed_user_ids`, must not be `None`")  # noqa: E501

        self._removed_user_ids = removed_user_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SetUsersRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SetUsersRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SetUsersRequest):
            return True

        return self.to_dict() != other.to_dict()
