# coding: utf-8

"""
    UiPath.WebApi 18.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 18.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from uipath_orchestrator_rest.configuration import Configuration


class UsersToggleOrganizationUnitRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'organization_unit_id': 'int',
        'toggle': 'bool'
    }

    attribute_map = {
        'organization_unit_id': 'organizationUnitId',
        'toggle': 'toggle'
    }

    def __init__(self, organization_unit_id=None, toggle=None, _configuration=None):  # noqa: E501
        """UsersToggleOrganizationUnitRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._organization_unit_id = None
        self._toggle = None
        self.discriminator = None

        self.organization_unit_id = organization_unit_id
        self.toggle = toggle

    @property
    def organization_unit_id(self):
        """Gets the organization_unit_id of this UsersToggleOrganizationUnitRequest.  # noqa: E501


        :return: The organization_unit_id of this UsersToggleOrganizationUnitRequest.  # noqa: E501
        :rtype: int
        """
        return self._organization_unit_id

    @organization_unit_id.setter
    def organization_unit_id(self, organization_unit_id):
        """Sets the organization_unit_id of this UsersToggleOrganizationUnitRequest.


        :param organization_unit_id: The organization_unit_id of this UsersToggleOrganizationUnitRequest.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and organization_unit_id is None:
            raise ValueError("Invalid value for `organization_unit_id`, must not be `None`")  # noqa: E501

        self._organization_unit_id = organization_unit_id

    @property
    def toggle(self):
        """Gets the toggle of this UsersToggleOrganizationUnitRequest.  # noqa: E501


        :return: The toggle of this UsersToggleOrganizationUnitRequest.  # noqa: E501
        :rtype: bool
        """
        return self._toggle

    @toggle.setter
    def toggle(self, toggle):
        """Sets the toggle of this UsersToggleOrganizationUnitRequest.


        :param toggle: The toggle of this UsersToggleOrganizationUnitRequest.  # noqa: E501
        :type: bool
        """
        if self._configuration.client_side_validation and toggle is None:
            raise ValueError("Invalid value for `toggle`, must not be `None`")  # noqa: E501

        self._toggle = toggle

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UsersToggleOrganizationUnitRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UsersToggleOrganizationUnitRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UsersToggleOrganizationUnitRequest):
            return True

        return self.to_dict() != other.to_dict()
