

MIN_PREDICTION_ID_LEN = 1
MAX_PREDICTION_ID_LEN = 128

# The maximum number of character for tag values
MAX_TAG_LENGTH = 20_000
MAX_TAG_LENGTH_TRUNCATION = 1_000


MAX_PAST_YEARS_FROM_CURRENT_TIME = 5
MAX_FUTURE_YEARS_FROM_CURRENT_TIME = 1

MAX_RAW_DATA_CHARACTERS = 50_000
MAX_RAW_DATA_CHARACTERS_TRUNCATION = 5_000

# The maximum number of embeddings
MAX_NUMBER_OF_EMBEDDINGS = 30
MAX_EMBEDDING_DIMENSIONALITY = 20_000

RESERVED_TAG_COLS = [

]

# Authentication via environment variables
SECRET_KEY_ENVVAR_NAME = "TFC_SECRET_KEY"
API_KEY_ENVVAR_NAME = "TFC_API_KEY"