from _typeshed import Incomplete
from amsdal_data.transactions.background.connections.base import WorkerConnectionBase as WorkerConnectionBase, WorkerMode as WorkerMode
from amsdal_data.transactions.background.schedule.config import SCHEDULE_TYPE as SCHEDULE_TYPE, ScheduleConfig as ScheduleConfig
from amsdal_data.transactions.background.schedule.crontab import Crontab as Crontab
from celery import Celery
from collections.abc import Callable as Callable
from typing import Any

class CeleryConnection(WorkerConnectionBase):
    app: Incomplete
    scheduled_tasks: Incomplete
    def __init__(self, app: Celery | None = None) -> None: ...
    def _convert_schedule(self, schedule: SCHEDULE_TYPE) -> Any: ...
    def register_transaction(self, func: Callable[..., Any], **transaction_kwargs: Any) -> None: ...
    def submit(self, func: Callable[..., Any], func_args: tuple[Any, ...], func_kwargs: dict[str, Any], transaction_kwargs: dict[str, Any]) -> None: ...
    def run_worker(self, init_function: Callable[..., None] | None = None, mode: WorkerMode = ...) -> None: ...
    def _populate_default_env_vars(self, connection_kwargs: dict[str, Any]) -> dict[str, Any]: ...
    def connect(self, **kwargs: Any) -> None: ...
    def disconnect(self) -> None: ...
    @property
    def is_connected(self) -> bool: ...
    @property
    def is_alive(self) -> bool: ...
