from amsdal_utils.query.data_models.order_by import OrderBy as OrderBy
from typing import Any

def get_nested_value(item: dict[str, Any], field_name: str) -> Any: ...
def sort_items(items: list[dict[str, Any]], order_by_list: list[OrderBy] | None) -> list[dict[str, Any]]: ...
