# -*- coding: utf-8 -*-


class TypeAttrEnum:
    required = "required"
    default_for_null = "default_for_null"
    itype = "itype"
    fields = "fields"


class TypeNameEnum:
    int = "int"
    tinyint = "tinyint"
    smallint = "smallint"
    bigint = "bigint"
    float = "float"
    double = "double"
    decimal = "decimal"
    str = "str"
    bin = "bin"
    bool = "bool"
    datetime = "datetime"
    timestamp = "timestamp"
    null = "null"
    set = "set"
    list = "list"
    struct = "struct"


class AwsDynamoDBTypeEnum:
    string = "S"
    number = "N"
    binary = "B"
    boolean = "BOOL"
    null = "NULL"
    list = "L"
    map = "M"
    number_set = "NS"
    string_set = "SS"
    binary_set = "BS"


class AwsGlueTypeEnum:
    tinyint = "tinyint"
    smallint = "smallint"
    bigint = "bigint"
    int = "int"
    float = "float"
    double = "double"
    decimal = "decimal"
    char = "char"
    string = "string"
    varchar = "varchar"
    binary = "binary"
    boolean = "boolean"
    date = "date"
    timestamp = "timestamp"
    interval = "interval"
    array = "array"
    set = "set"
    map = "map"
    struct = "struct"
    union = "union"


class SparkTypeEnum:
    tinyint = "tinyint"
    smallint = "smallint"
    int = "int"
    integer = "integer"
    long = "long"
    bigint = "bigint"
    float = "float"
    double = "double"
    decimal = "decimal"
    string = "string"
    byte = "byte"
    binary = "binary"
    boolean = "boolean"
    short = "short"
    date = "date"
    timestamp = "timestamp"
    timestampntz = "timestampntz"
    calendarinterval = "calendarinterval"
    yearmonthinterval = "yearmonthinterval"
    dayinterval = "dayinterval"
    null = "null"
    array = "array"
    map = "map"
    struct = "struct"
    udt = "udt"
