from _typeshed import Incomplete
from numpy.core.overrides import set_module as set_module

class _FileOpeners:
    def __init__(self) -> None: ...
    def keys(self): ...
    def __getitem__(self, key): ...

def open(path, mode: str = 'r', destpath=..., encoding: Incomplete | None = None, newline: Incomplete | None = None): ...

class DataSource:
    def __init__(self, destpath=...) -> None: ...
    def __del__(self) -> None: ...
    def abspath(self, path): ...
    def exists(self, path): ...
    def open(self, path, mode: str = 'r', encoding: Incomplete | None = None, newline: Incomplete | None = None): ...

class Repository(DataSource):
    def __init__(self, baseurl, destpath=...) -> None: ...
    def __del__(self) -> None: ...
    def abspath(self, path): ...
    def exists(self, path): ...
    def open(self, path, mode: str = 'r', encoding: Incomplete | None = None, newline: Incomplete | None = None): ...
    def listdir(self): ...
