from typing import Final, Literal

EXPECTED_KEYS: Final[set[str]]
MAGIC_PREFIX: Final[bytes]
MAGIC_LEN: Literal[8]
ARRAY_ALIGN: Literal[64]
BUFFER_SIZE: Literal[262144]

def magic(major, minor) -> None: ...
def read_magic(fp) -> None: ...
def dtype_to_descr(dtype) -> None: ...
def descr_to_dtype(descr) -> None: ...
def header_data_from_array_1_0(array) -> None: ...
def write_array_header_1_0(fp, d) -> None: ...
def write_array_header_2_0(fp, d) -> None: ...
def read_array_header_1_0(fp) -> None: ...
def read_array_header_2_0(fp) -> None: ...
def write_array(fp, array, version=..., allow_pickle=..., pickle_kwargs=...) -> None: ...
def read_array(fp, allow_pickle=..., pickle_kwargs=...) -> None: ...
def open_memmap(filename, mode=..., dtype=..., shape=..., fortran_order=..., version=...) -> None: ...
