# coding: utf-8

"""
    UiPath.WebApi 18.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 18.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from uipath_orchestrator_rest.configuration import Configuration


class ReleasesUpdateToSpecificPackageVersionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'package_version': 'str'
    }

    attribute_map = {
        'package_version': 'packageVersion'
    }

    def __init__(self, package_version=None, _configuration=None):  # noqa: E501
        """ReleasesUpdateToSpecificPackageVersionRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._package_version = None
        self.discriminator = None

        self.package_version = package_version

    @property
    def package_version(self):
        """Gets the package_version of this ReleasesUpdateToSpecificPackageVersionRequest.  # noqa: E501


        :return: The package_version of this ReleasesUpdateToSpecificPackageVersionRequest.  # noqa: E501
        :rtype: str
        """
        return self._package_version

    @package_version.setter
    def package_version(self, package_version):
        """Sets the package_version of this ReleasesUpdateToSpecificPackageVersionRequest.


        :param package_version: The package_version of this ReleasesUpdateToSpecificPackageVersionRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and package_version is None:
            raise ValueError("Invalid value for `package_version`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                package_version is not None and len(package_version) < 1):
            raise ValueError("Invalid value for `package_version`, length must be greater than or equal to `1`")  # noqa: E501

        self._package_version = package_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReleasesUpdateToSpecificPackageVersionRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReleasesUpdateToSpecificPackageVersionRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ReleasesUpdateToSpecificPackageVersionRequest):
            return True

        return self.to_dict() != other.to_dict()
